### ISSUE TITLE
How does object_slam get the correct depth cloud when whether_sample_cam_roll_pitch is false?

### ISSUE THREAD

**Issue by drscopus** [shichaoy/cube_slam#13]
The package object_slam can build the map for a cuboid. I run the online_detect_mode of object_slam with different parameter settings. 
When the parameter "detect_cuboid_obj.whether_sample_cam_roll_pitch" is set to be true, the /slam_odom_pose is close to the /truth_odom_pose, the /cubes_opti_hist is also close to the /cubes_raw_frame. The built depth cloud of the cuboid is great.
However, when the parameter "detect_cuboid_obj.whether_sample_cam_roll_pitch" is set to be false, the /slam_odom_pose is far from the /truth_odom_pose, the /cubes_opti_hist is also far from the /cubes_raw_frame. But in this case the built depth cloud of the cuboid is same as the "detect_cuboid_obj.whether_sample_cam_roll_pitch" is true. 
![rviz_screenshot_2019_11_06-16_20_48](https://user-images.githubusercontent.com/9296543/68282242-4a5ddc80-00b4-11ea-9655-4bc7624f1fce.png)
As above image shows, the blue /slam_odom_pose drifts far from red /truth_odom_pose. Both the /cubes_opti_hist and /cubes_raw_frame are far from the built depth cloud. It seems that the depth cloud is correct.

So when the camera poses drifts so much far from the truth poses, why can it still build the correct  map(depth cloud)?
Thanks!

**Comment by shichaoy** [comment]
Hi the depth cloud is actually ground truth depth at ground truth camera pose. So it is always correct. It is only used for visualization purpose, to see whether optimized cuboid align with truth cloud.

we need to set whether_sample_cam_roll_pitch = true for this scenario. because this is 3D camera movement. roll/pitch has strong effect on vanishing point. Since we don't have accurate orientation estimation, we need to sample camera roll/pitch
