### ISSUE TITLE
process has died when run orb_object_slam

### ISSUE THREAD

**Issue by GuaguaguaLiu** [shichaoy/cube_slam#21]
Hello, thanks for your great job and open source sharing.
I try the command ‘roslaunch orb_object_slam mono_dynamic.launch’, but there is a problem that '[ros_mono-3] process has died [pid 10101, exit code -11...'
I don't know why. Look forward to your reply. Thank you!
![1](https://user-images.githubusercontent.com/45514347/70505447-081c3500-1b63-11ea-840f-683dc550e96d.png)
![2](https://user-images.githubusercontent.com/45514347/70505450-09e5f880-1b63-11ea-8bba-cbe5878dcea2.png)

**Comment by MinaHenein** [comment]
Hey @GuaguaguaLiu 
I'm facing the same error, could you fix it? and how? please

**Comment by GuaguaguaLiu** [comment]
Hello，I think you may need to get the 'ORBvoc. bin' in "cube_slam/orb_object_slam/Vocabulary/"

**Comment by MinaHenein** [comment]
Thanks! All good now

**Comment by Hello-Water** [comment]
Hello, @GuaguaguaLiu 
when I tried the command ‘roslaunch orb_object_slam mono.launch’, there was a problem about 'malloc(): memory corruption' like the following pictures:
![image](https://user-images.githubusercontent.com/30867133/115192265-2ada3880-a11d-11eb-9483-787f11f5d3f6.png)
![image](https://user-images.githubusercontent.com/30867133/115192289-3299dd00-a11d-11eb-96cf-26edc4a3ec63.png)

whether you faced the error before?
Is it because the  'ORBvoc. bin' ?

but when I run './Vocabulary/bin_vocabulary', this problem './Vocabulary/bin_vocabulary: error while loading shared libraries: libDBoW2.so: cannot open shared object file: No such file or directory' occurred.

Looking forward to your response to the above questions. Thank you!
