### ISSUE TITLE
how to triangulate a dynamic point?

### ISSUE THREAD

**Issue by zhangjun-xyz** [shichaoy/cube_slam#8]
In your paper _CubeSLAM: Monocular 3D Object SLAM_, you propose to triangulate a dynamic point:
![image](https://user-images.githubusercontent.com/12016132/63096694-20a78480-bfa1-11e9-9a8f-2bef4145cec6.png)
In real initialization case, how do you get Delta T?

**Comment by shichaoy** [comment]
hi, we triangulate points only between keyframes. Object pose in last KF is already optimized, accurate to some extent.  but object pose in current keyframe just depends on the single image detection result. so it may not be accurate but since I didn't depend on the triangulated 3D points for latter point tracking (I use 2D KLT), it is fine not to be that accurate. It is only used as initialization for further BA optimization.
